//
//  PersonalCardShowcase.swift
//
//  {{OWNER_NAME}}'s personalized holographic card, generated by the
//  holo-card-designer skill. Drag the card to tilt it in 3D.
//
//  Template tokens ({{…}}) must all be replaced before compiling.
//

import SwiftUI
import ShaderCards

struct PersonalCardShowcase: View {
  /// The user's asset, loaded once. Falls back to the base gradient below
  /// when the file is missing so the view never renders a gray placeholder.
  private static let portraitData: Data? =
    try? Data(contentsOf: URL(fileURLWithPath: "{{IMAGE_PATH}}"))

  /// Opaque backdrop in {{OWNER_NAME}}'s palette; only visible if the
  /// image fails to load or carries transparency.
  private static let baseGradient: [Color] = [
    {{BASE_GRADIENT_STOPS}}
  ]

  /// Translucent stops layered over the photo to marry it to the foil.
  /// Keep every stop's opacity in 0.10–0.35.
  private static let tintScrim: [Color] = [
    {{TINT_SCRIM_STOPS}}
  ]

  private static let card: Card = {
    var art: CardArt = .gradient(baseGradient)
    if let data = portraitData {
      art = .layered([
        .gradient(baseGradient),
        .image(data),
        .gradient(tintScrim),
      ])
    }

    return CardBuilder(name: "{{CARD_NAME}}", element: .{{ELEMENT}})
      .hp({{HP}})
      .rarity(.{{RARITY}})
      .art(art)
      .layout(.{{LAYOUT}})
      .finish({{FINISH}})
      .attack("{{ATTACK_1_NAME}}", cost: [.{{ELEMENT}}, .colorless], damage: "{{ATTACK_1_DAMAGE}}")
      .attack("{{ATTACK_2_NAME}}", cost: [.{{ELEMENT}}, .{{ELEMENT}}], damage: "{{ATTACK_2_DAMAGE}}")
      .species("{{ROLE_TITLE}}")
      .flavor("{{FLAVOR_TEXT}}")
      .setNumber("{{SET_NUMBER}}")
      .illustrator("{{OWNER_NAME}}")
      .build()
  }()

  var body: some View {
    ZStack {
      // Near-black stage with a faint {{ELEMENT}} color cast so the
      // foil highlights carry.
      RadialGradient(
        colors: [
          Color(red: {{STAGE_CENTER_RGB}}),
          Color(red: 0.03, green: 0.03, blue: 0.05),
        ],
        center: .center,
        startRadius: 40,
        endRadius: 620
      )
      .ignoresSafeArea()

      VStack(spacing: 26) {
        Text("{{HEADLINE}}")
          .font(.system(size: 22, weight: .bold, design: .rounded))
          .foregroundStyle(.white.opacity(0.92))

        TradingCardView(Self.card, width: 320)

        Text("Drag to tilt")
          .font(.system(size: 12, weight: .medium))
          .foregroundStyle(.white.opacity(0.5))
      }
      .padding(.vertical, 32)
    }
    .preferredColorScheme(.dark)
  }
}

#Preview {
  PersonalCardShowcase()
}
